name: Update AUR Package

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    env:
      HAS_AUR_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY != '' }}
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git sudo openssh

      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update PKGBUILD and .SRCINFO
        shell: bash
        run: |
          sudo -u builder ./update-pkgver.sh

      - name: Check for changes
        id: git_check
        run: |
          if git diff --quiet PKGBUILD .SRCINFO; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            status=$?
            if [ $status -eq 1 ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "git diff failed with status $status" >&2
              exit $status
            fi
          fi

      - name: Commit and push to GitHub
        if: steps.git_check.outputs.changed == 'true'
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m ":arrow_up: Auto-update to $(grep -P '^pkgver=' PKGBUILD | cut -d= -f2)"
          git push

      - name: Setup SSH keys
        if: steps.git_check.outputs.changed == 'true' && env.HAS_AUR_KEY == 'true'
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Push to AUR
        if: steps.git_check.outputs.changed == 'true' && env.HAS_AUR_KEY == 'true'
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 aur.archlinux.org >> ~/.ssh/known_hosts

          # Clone the AUR repository to a temporary directory
          AUR_DIR=$(mktemp -d)
          git config --global --add safe.directory "$AUR_DIR"
          git clone ssh://aur@aur.archlinux.org/fsh-sushi-git.git "$AUR_DIR"

          # Copy necessary files to the AUR directory
          cp PKGBUILD .SRCINFO .gitignore "$AUR_DIR"

          # Commit and push to AUR
          cd "$AUR_DIR"
          git add PKGBUILD .SRCINFO .gitignore
          if git diff --quiet --cached; then
            echo "No changes to commit to AUR"
          else
            pkgver=$(grep -P '^pkgver=' PKGBUILD | cut -d= -f2)
            git commit -m "Auto-update to $pkgver"
            git push origin master
          fi
